# Jekyll configuration for NgKore GitHub Pages

# Site settings
title: NgKore
description: "Driving OPEN SOURCE Innovation for the FUTURE"
url: "https://ngkore.github.io" # Your GitHub Pages domain
baseurl: "/ngkore-website" # Your repository name

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files and directories
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - .github
  - dev-server.py
  - dev-server.js
  - "*.script"

# Include files that start with underscore
include:
  - _pages

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Permalink structure
permalink: pretty

# Sass configuration
sass:
  sass_dir: assets/css
  style: compressed

# Compression
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
